# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build_and_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest #the OS on which this job is executed

    steps:
    - name: Checkout repo on machine
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install packages/dependencies
      run: npm install 
    - name: Start the app 
      run: npm run start & #starts the app in background process
    - name: Run tests
      run: npm test 

  security_test:

    runs-on: ubuntu-latest #the OS on which this job is executed

    steps:
    - name: Checkout repo on machine
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install packages/dependencies
      run: npm install
    - name: Run security tests
      run: npm audit 

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_DEPLOY_HOOK }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
